name: m3e_expandable
description: "A Flutter package providing expressive, Material 3 expandable card lists with spring-driven animations and dynamic border radius."
version: 0.0.1
homepage: https://github.com/Mudit200408/m3e_expandable
repository: https://github.com/Mudit200408/m3e_expandable 
issue_tracker: https://github.com/Mudit200408/m3e_expandable/issues


topics:
  - ui
  - material-3-expressive
  - m3e
  - expandable
  - physics

environment:
  sdk: ^3.11.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  motor: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: